cmake_minimum_required(VERSION 3.10)
project(yolov8_multicard LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(SOPHON_DEMO_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../../third_party/sophon-demo" CACHE PATH "Official demo repository")
set(YOLO_DIR "${SOPHON_DEMO_DIR}/sample/YOLOv8_plus_det/cpp/yolov8_bmcv")
set(FFMPEG_DIR /opt/sophon/sophon-ffmpeg-latest/lib/cmake CACHE PATH "FFmpeg config")
set(OpenCV_DIR /opt/sophon/sophon-opencv-latest/lib/cmake/opencv4 CACHE PATH "OpenCV config")
find_package(FFMPEG REQUIRED)
find_package(OpenCV REQUIRED)
find_package(libsophon REQUIRED)
find_package(Threads REQUIRED)
include_directories(${YOLO_DIR} ${FFMPEG_INCLUDE_DIRS} ${OpenCV_INCLUDE_DIRS} ${LIBSOPHON_INCLUDE_DIRS})
link_directories(${FFMPEG_LIB_DIRS} ${OpenCV_LIB_DIRS} ${LIBSOPHON_LIB_DIRS})
add_executable(yolov8_multicard.pcie main.cpp "${YOLO_DIR}/yolov8_det.cpp")
target_link_libraries(yolov8_multicard.pcie ${FFMPEG_LIBS} ${OpenCV_LIBS} ${the_libbmlib.so} ${the_libbmrt.so} ${the_libbmcv.so} Threads::Threads)
